재환김
yigim/yigim pull request #11
Opened 2020-08-29 15:15 UTC by JaeHoanKim

문제 응시자 부분 플로우 수정했습니다.

//Router에 props 넣는 것 승건님이 알려주신 방법대로 하니 잘 작동했습니다!

한 일

응시자 부분 컴포넌트 추가(ProbSolveLinkInput)
응시자가 이름 입력하고 문제 풀고 나면 결과창에 응시자 이름, 점수 등 표시되도록 함

2020-09-05 07:16 UTC, geongun20 requested changes

2020-09-05 07:16 UTC, geongun20 commented on packages/yigim-client/src/components/probsolving.js
> +    while (i < prob.answer.length) {
while대신 forEach, map, reduce를 사용해주세요.
[https://velog.io/@1571min/TIL20.02.20-JavaScript%ED%95%A8%EC%88%98%ED%98%95-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D-forEach-map-filter-reduce](https://velog.io/@1571min/TIL20.02.20-JavaScript%ED%95%A8%EC%88%98%ED%98%95-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D-forEach-map-filter-reduce)

2020-09-05 15:28 UTC, JaeHoanKim commented on packages/yigim-client/src/components/probsolving.js
> +    while (i < prob.answer.length) {
수정 완료했습니다!

2020-09-06 09:20 UTC, geongun20 submitted a review, later dismissed

2020-09-06 11:22 UTC, taxis853 submitted a review, later dismissed

2020-09-06 14:35 UTC, kyungwon-lee approved these changes

2020-09-06 14:36 UTC, merged