문제 푸는 화면의 컴포넌트 추가 및 대략적인 구성 완료했습니다
yigim/yigim pull request #7
Opened 2020-08-23 17:05 UTC by JaeHoanKim

-한 일
App component에 probsolve router 추가
probsolve component 대략적인 구성
-할 일
버튼 번호와 출제자의 정답 번호 비교해서 정답, 오답 나타나게 하기
문제를 풀고 나면 다음 문제로 가는 버튼이 생기게 하기

관련 질문사항) 처음에는 생각치 못했던 화면들이 중간중간 삽입되면서 이름이 약간 덜 직관적이게 되었는데,
ex. 문제 푸는 사람의 경우 문제 풀기 직전 화면 컴포넌트가 probsolving, 문제 푸는 화면 컴포넌트가 probsolve
이런 건 오류만 없으면 크게 상관 없나요??

2020-08-24 10:10 UTC, JaeHoanKim commented
-한 일
문제를 푸는 동안 자기 점수/전체 점수가 나타나도록 함
한 번 풀고 나면 정답 수정 없이 다음 문제로만 갈 수 있도록 함
1번부터 10번까지 모든 문제들 풀고 최종적으로 probsolvedone 페이지로 이동하도록 함
-할 일
문제의 정답과 비교해서 정답일 때, 오답일 때 동그라미, 틀린 표시 나타나도록 효과 추가 
문제 출제 시 문제 갱신 기능

2020-08-24 12:06 UTC, geongun20 commented
> 관련 질문사항) 처음에는 생각치 못했던 화면들이 중간중간 삽입되면서 이름이 약간 덜 직관적이게 되었는데,
> ex. 문제 푸는 사람의 경우 문제 풀기 직전 화면 컴포넌트가 probsolving, 문제 푸는 화면 컴포넌트가 probsolve
> 이런 건 오류만 없으면 크게 상관 없나요??

작명을 잘하는 것이 협업의 측면에서 많이 중요합니다.

2020-08-24 12:19 UTC, geongun20 requested changes
본래 생각했던 것은 문제를 만드는 뷰와 문제를 푸는 뷰가 많이 비슷하므로 하나의 뷰로 만들고 옵션에 따라 문제를 만드는 뷰/문제를 푸는 뷰로 달리 보이도록 구현이 가능할까요?

2020-08-24 12:19 UTC, geongun20 commented on packages/yigim-client/src/App.js
>            <Route exact path="/probmakeready/:id/0" component={ProbMakeReady}></Route>
url 같은 경우는 kebab-case로 작성해주세요.
참고링크: https://medium.com/better-programming/string-case-styles-camel-pascal-snake-and-kebab-case-981407998841

2020-08-24 12:19 UTC, geongun20 commented on packages/yigim-client/src/components/probsolve.js
> +        var prob = this.state.userdata[Number(this.probNumber)];
number로 타입 캐스팅한 이유는 무엇인가요?

2020-08-24 12:19 UTC, geongun20 commented on packages/yigim-client/src/components/probsolve.js
> +        }
while이나 for문 대신 forEach, map, filter, reduce를 사용해주세요.

2020-08-24 13:43 UTC, taxis853 reviewed
userdata의 score는 난이도에 따라 결정하면 되는 것이죠?
난이도에 따른 배점을 실제 수학 모의고사 처럼 4/3/2로 해도 될까요?

2020-08-24 13:44 UTC, taxis853 approved these changes

2020-08-24 13:44 UTC, taxis853 approved these changes

2020-08-24 13:45 UTC, taxis853 approved these changes

2020-08-24 14:01 UTC, taxis853 reviewed
그리고 CSS파일에서 className의 첫글자는 대문자로 통일하면 좋겠습니다!

2020-08-24 15:24 UTC, JaeHoanKim commented on packages/yigim-client/src/components/probsolve.js
> +        var prob = this.state.userdata[Number(this.probNumber)];
덧셈 연산을 할 떄, number로 타입 캐스팅을 해주지 않은 경우 0 + 1 = 01 과 같은 결과를 내는 걸 본 적이 있어서 number로 처리해줬습니다!

2020-08-24 15:44 UTC, JaeHoanKim commented
> * 본래 생각했던 것은 문제를 만드는 뷰와 문제를 푸는 뷰가 많이 비슷하므로 하나의 뷰로 만들고 옵션에 따라 문제를 만드는 뷰/문제를 푸는 뷰로 구분하여 달리 보이도록 하는 거였습니다. 그렇게 구현이 가능할까요?
> * 현재 상황에서는 겹치는 코드가 별로 없지만 앞으로 문제를 푸는 UI 가 다양해 지면 겹치는 코드가 많아지고 불필요한 코드의 중복이 많아 질 수 있을 것 같습니다. 앞으로 만들어야할 문제 풀기/만들기 UI가 많이 남은 것이 맞나요?

2020-08-24 15:50 UTC, JaeHoanKim commented
1. 네 가능할 것 같습니다! 
그런데 그렇게 되면, 현재 문제를 만드는 뷰에서는 문제를 수정하는 기능과, 출제자가 답변을 체크하고 그것을 변경할 수 있는 기능이 있고, 문제를 푸는 뷰에서는 문제를 수정하지 못하고 한 번 문제를 풀고 나면 다른 답변 선택 기능이 비활성화되고 다음 문제 버튼만이 활성화되도록 되어 있어서 합치는 과정에서 약간 번거로움이 있을 것 같습니다.
2. 이제 더 만들어야 할 UI는 성적 등수 관련 부분만 남았습니다. 문제 푸는 뷰와 만드는 뷰를 합쳐보고, 응시 전 주의사항도 지금은 뷰를 분리해서 만들어놓았는데 이것도 하나로 합치면 중복이 줄어들 것 같습니다!

2020-08-24 16:04 UTC, JaeHoanKim commented
-한 일
피드백된 것들 일부분 수정
url kebab-case로 변경
component 이름 수정(probsolving->problinkinput)
-할 일
문제 푸는 뷰와 문제 만드는 뷰 합치기
출제자, 응시자 주의사항 합치기

2020-08-25 05:39 UTC, taxis853 approved these changes

2020-08-25 07:47 UTC, JaeHoanKim commented
> userdata의 score는 난이도에 따라 결정하면 되는 것이죠?
> 난이도에 따른 배점을 실제 수학 모의고사 처럼 4/3/2로 해도 될까요?

2020-08-25 07:48 UTC, JaeHoanKim commented
좋습니다!

2020-08-26 14:24 UTC, geongun20 commented
**한 일
-컴포넌트 이름 재정비 및 이용되지 않는 파일들 삭제(Userinfo_Fc, QuestionList)
-문제 풀기/만들기 준비 화면 하나의 컴포넌트(ProbReady)로 병합
-url kebab-case로 통일
-문제푸는 컴포넌트 구성
**할 일
-문제 푸는/만드는 컴포넌트 병합
-className 첫 글자 대문자로 바꾸기
-정답/오답일 때 채점되는 이미지 추가
-문제 출제 시 문제 추천리스트 만들기

2020-08-26 14:34 UTC, geongun20 approved these changes

2020-08-26 14:34 UTC, geongun20 commented on packages/yigim-client/src/components/probmaking.js
> +        var answers_each=data.answer.map(string => string)
```suggestion
        var answers_each=data.answer
```
와 같습니다. 불필요한 map 사용입니다.

2020-08-26 14:35 UTC, merged