난이도 기능 추가 및 디자인 조금 수정
yigim/yigim pull request #8
Opened 2020-08-24 14:53 UTC by taxis853

-한 일 
probmaking.js 에서 난이도 설정을 추가 (난이도는 상/중/하 중에서 선택할 수 있고, 각각 score는 4/3/2점 으로 설정)
문제 질문의 폰트를 HY태고딕에서 NanumMyeongjo로 수정
 
-할 일 
이 문제 건너뛰기 기능 추가
항목 선택시 체크 이미지가 뜨는 기능 추가

2020-08-24 15:53 UTC, JaeHoanKim commented on packages/yigim-client/src/components/probmaking.js
> +                        />
난이도 multi-select 방지 기능과 선택되지 않으면 default 값으로 난이도가 중으로(예시입니다) 배정되는 기능도 추가되면 좋을 것 같습니다!

2020-08-24 15:54 UTC, JaeHoanKim approved these changes
확인했습니다!

2020-08-25 05:49 UTC, taxis853 commented on packages/yigim-client/src/components/probmaking.js
> +                        />
현재 default 난이도는 '중' (score: 3)으로 되어있고, 난이도 버튼을 누르면 score 값이 바뀌게 해놓았습니다. 
-> 이 부분에 대하여 사용자에게 default 값이 난이도 '중' 이라고 시각적인 언급을 해주는 것이 좋을까요? 

여러번 select를 하면 마지막에 select한 난이도로 score가 설정되는 방식입니다. multi-select에 대한 우려는 하지 않으셔도 될 것 같습니다.

2020-08-26 14:38 UTC, geongun20 requested changes

2020-08-26 14:38 UTC, geongun20 commented on packages/yigim-client/src/components/probmaking.js
> +            for(j = 1; j <= 3; j ++)
for나 while문은 사용하지 않는것이 좋습니다. forEach, map, reduce 등을 사용해 주세요.

2020-08-28 09:49 UTC, JaeHoanKim commented on packages/yigim-client/src/components/probmaking.js
> +                        />
아하 radio로 되어있었군요! 착각했습니다 ㅠㅠ 음 중이라고 시각적 언급을 해주는 것도 좋을 것 같습니다!

2020-08-28 09:50 UTC, JaeHoanKim approved these changes

2020-08-29 08:08 UTC, taxis853 commented on packages/yigim-client/src/components/probmaking.js
> +            for(j = 1; j <= 3; j ++)
수정사항 반영했습니다

2020-08-29 13:25 UTC, JaeHoanKim approved these changes
코드 확인했습니다!

2020-08-29 14:21 UTC, geongun20 approved these changes

2020-08-29 14:21 UTC, geongun20 commented
@taxis853 master위로 rebase한 뒤 force push 해주세요~

2020-08-30 06:11 UTC, closed without merging